name: CD

on:
  workflow_dispatch: {}
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    runs-on: self-hosted   # lub etykieta twojego runnera, np. ['self-hosted', 'linux']
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Pull latest image
        run: |
          docker pull ${{ secrets.REGISTRY_URL }}/flask-devops:latest

      - name: Docker Compose pull
        run: |
          docker compose pull

      - name: Docker Compose up
        run: |
          docker compose up -d
